services:
 postgres:
   image: postgres:latest
   container_name: auctions
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgrespw
    POSTGRES_DB: Auctions
   ports:
     - "5432:5432"
   volumes:
     - pgdata:/var/lib/postgresql/data
volumes:
 pgdata: